service: sw-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getAll:
    handler: src/characters/handler.getAll
    events:
     - http:
        path: characters
        method: get
        cors: true
  
  create:
    handler: src/characters/handler.create
    events:
     - http:
        path: characters
        method: post
        cors: true

  delete:
    handler: src/characters/handler.deleteOne
    events:
     - http:
        path: characters
        method: delete
        cors: true

plugins:
  - serverless-offline
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false