service: sw-api

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x


functions:
  find:
    handler: src/characters/handler.find
    events:
     - http:
        path: characters
        method: get
        cors: true

  findOne:
    handler: src/characters/handler.findOne
    events:
     - http:
        path: characters/{userName}
        method: get
        request: 
          parameters: 
             paths: 
               userName: true
        cors: true
  
  create:
    handler: src/characters/handler.create
    events:
     - http:
        path: characters
        method: post
        cors: true

  update:
    handler: src/characters/handler.update
    events:
     - http:
        path: characters
        method: put
        cors: true

  delete:
    handler: src/characters/handler.deleteOne
    events:
     - http:
        path: characters
        method: delete
        cors: true

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin

custom:
  esbuild:
    bundle: true
    minify: false